version: '2'

services:
  # Appium Docker Android
  appium_android_device:
    image: appium/appium
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ~/.android:/root/.android
    environment:
      - CONNECT_TO_GRID=True
      - SELENIUM_HOST=selenium_hub
      # Enable it for msite testing
      # - BROWSER_NAME=chrome
