engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_paths:
      - "packages/**/distribution/"
      - "features/"
      - "**/node_modules/"
      - script/
      - "**/test/"
  eslint:
    enabled: true
ratings:
  paths:
    - "**.js"