files:
  - ./example/flow/**/*.js
  - ./example/hooks/**/*.js
  - ./example/subflow/**/*.js
  - ./example/suites/**/*.js

server:
  port: 3000
  
mocha:
  require:
    # - babel-register
    - ./example/setup.js
