files:
  - ./example/flow/**/*.js
  - ./example/hooks/**/*.js
  - ./example/subflow/**/*.js
  - ./example/suites/**/*.js

server:
  port: 3000
  
tags:
  - core

mocha:
  reporter: 'list'
  bail: true
  require:
    - babel-register
    - ./example/setup.js
